FROM eclipse-temurin:17-jdk-alpine
VOLUME /tmp
# Se usi Maven (genera il file in target/):
COPY target/*.jar app.jar
# (Se usi Gradle, sostituisci la riga sopra con: COPY build/libs/*.jar app.jar)

ENTRYPOINT ["java","-jar","/app.jar"]